[OnlineSubsystem]
DefaultPlatformService=Dungeons
PollingIntervalInMs=20

[OnlineSubsystemPS4]
bEnabled=true

[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName=GameNetDriver,DriverClassName=/Script/OnlineSubsystemPS4.PS4NetDriver,DriverClassNameFallback=/Script/OnlineSubsystemUtils.IpNetDriver)
+NetDriverDefinitions=(DefName=BackupGameNetDriver,DriverClassName=/Script/OnlineSubsystemDungeons.DungeonsNetDriver,DriverClassNameFallback=/Script/OnlineSubsystemUtils.IpNetDriver)

[/Script/PS4PlatformEditor.PS4TargetSettings]
bUsesDownloadZero=True

[/Script/Engine.NetworkSettings]
n.VerifyPeer=true

;[/Script/PS4PlatformEditor.PS4TargetSettings]
;TitleID=ED2690-NPXX53438_00-MINECRAFTDUNGEON


[/Script/Engine.RendererSettings]
; D11.DH Fix for rain particles in Soggy Swamp and Dingy Jungle
r.AllowOcclusionQueries=False
r.TonemapperGamma=2.2
Gamma=2.2

[PS4Application]
DefaultAgeRestriction=10
+CountryAgeRestrictions=(Country="ru",Age=6)
+CountryAgeRestrictions=(Country="au",Age=8)
+CountryAgeRestrictions=(Country="us",Age=10)
+CountryAgeRestrictions=(Country="ca",Age=10)
+CountryAgeRestrictions=(Country="mx",Age=10)
+CountryAgeRestrictions=(Country="br",Age=10)
+CountryAgeRestrictions=(Country="ar",Age=10)
+CountryAgeRestrictions=(Country="bo",Age=10)
+CountryAgeRestrictions=(Country="cl",Age=10)
+CountryAgeRestrictions=(Country="co",Age=10)
+CountryAgeRestrictions=(Country="cr",Age=10)
+CountryAgeRestrictions=(Country="ec",Age=10)
+CountryAgeRestrictions=(Country="sv",Age=10)
+CountryAgeRestrictions=(Country="gt",Age=10)
+CountryAgeRestrictions=(Country="hn",Age=10)
+CountryAgeRestrictions=(Country="ni",Age=10)
+CountryAgeRestrictions=(Country="pa",Age=10)
+CountryAgeRestrictions=(Country="py",Age=10)
+CountryAgeRestrictions=(Country="pe",Age=10)
+CountryAgeRestrictions=(Country="uy",Age=10)

