[/Script/Engine.GameSession]
;Always on chat audio
bRequiresPushToTalk=false

[/Script/MoviePlayer.MoviePlayerSettings]
+StartupMovies=blank_splash720
+StartupMovies=microsoft_splash1080
+StartupMovies=mojang_splash1080
+StartupMovies=double11_splash1080
+StartupMovies=unreal_splash1080
+StartupMovies=loader_splash1080

[EntitlementMapping]
+EntitlementMap=(EntitlementName="game_dungeons_dlc_1", PlatformSkuId="DUNGEONSPS4DLC10")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_2", PlatformSkuId="DUNGEONSPS4DLC20")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_1", PlatformSkuId="DUNGEONSHERODLC0")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_2", PlatformSkuId="DUNGEONSHERODLC0")
+EntitlementMap=(EntitlementName="game_dungeons_hero_cape_1", PlatformSkuId="DUNGEONSHERODLC0")
+EntitlementMap=(EntitlementName="game_dungeons_hero_skin_1", PlatformSkuId="DUNGEONSHERODLC0")
+EntitlementMap=(EntitlementName="game_dungeons_hero_skin_2", PlatformSkuId="DUNGEONSHERODLC0")
+EntitlementMap=(EntitlementName="game_dungeons_hero_pet_1", PlatformSkuId="DUNGEONSHERODLC0")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_3", PlatformSkuId="DUNGEONSPS4DLC30")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_4", PlatformSkuId="DUNGEONSPS4DLC40")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_5", PlatformSkuId="DUNGEONSPS4DLC50")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_6", PlatformSkuId="DUNGEONSPS4DLC60")


[ProductIdMapping]
+ProductMap=(DlcName="HeroDLC", PlatformProductId="DUNGEONSHERODLC0")
+ProductMap=(DlcName="JungleDLC", PlatformProductId="DUNGEONSPS4DLC10")
+ProductMap=(DlcName="IceDLC", PlatformProductId="DUNGEONSPS4DLC20")
+ProductMap=(DlcName="MountainsDLC", PlatformProductId="DUNGEONSPS4DLC30")
+ProductMap=(DlcName="NetherDLC", PlatformProductId="DUNGEONSPS4DLC40")
+ProductMap=(DlcName="OceansDLC", PlatformProductId="DUNGEONSPS4DLC50")
+ProductMap=(DlcName="TheEndDLC", PlatformProductId="DUNGEONSPS4DLC60")