[Demo]
PlayTimeMins=15

[/Script/MoviePlayer.MoviePlayerSettings]
+StartupMovies=microsoft_splash720
+StartupMovies=mojang_splash720
+StartupMovies=double11_splash720
+StartupMovies=unreal_splash720
+StartupMovies=loader_splash720

[/Script/UnrealEd.ProjectPackagingSettings]
+MovieBlackList="End_C1_Stronghold_Intro"
+MovieBlackList="End_C2_Stronghold_Outro"
+MovieBlackList="End_C3_BrokenCitadel_BossIntro"
+MovieBlackList="End_C4_BrokenCitadel_Outro_Part1"
+MovieBlackList="End_C4_BrokenCitadel_Outro_Part2"

[EntitlementMapping]
+EntitlementMap=(EntitlementName="game_dungeons_dlc_1", PlatformSkuId="1")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_2", PlatformSkuId="2")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_1", PlatformSkuId="3")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_2", PlatformSkuId="3")
+EntitlementMap=(EntitlementName="game_dungeons_hero_cape_1", PlatformSkuId="3")
+EntitlementMap=(EntitlementName="game_dungeons_hero_skin_1", PlatformSkuId="3")
+EntitlementMap=(EntitlementName="game_dungeons_hero_skin_2", PlatformSkuId="3")
+EntitlementMap=(EntitlementName="game_dungeons_hero_pet_1", PlatformSkuId="3")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_3", PlatformSkuId="4")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_4", PlatformSkuId="5")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_5", PlatformSkuId="6")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_6", PlatformSkuId="7")


[ProductIdMapping]
+ProductMap=(DlcName="JungleDLC", PlatformProductId="1")
+ProductMap=(DlcName="IceDLC", PlatformProductId="2")
+ProductMap=(DlcName="HeroDLC", PlatformProductId="3")
+ProductMap=(DlcName="MountainsDLC", PlatformProductId="4")
+ProductMap=(DlcName="NetherDLC", PlatformProductId="5")
+ProductMap=(DlcName="OceansDLC", PlatformProductId="6")
+ProductMap=(DlcName="TheEndDLC", PlatformProductId="7")

;[/Script/Dungeons.OnlineGame]
;DisableOnlineGame=true