[OnlineSubsystem]
DefaultPlatformService=Dungeons
PollingIntervalInMs=20

[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName=GameNetDriver,DriverClassName=/Script/OnlineSubsystemDungeons.DungeonsNetDriver,DriverClassNameFallback=/Script/OnlineSubsystemUtils.IpNetDriver)

[/Script/SwitchRuntimeSettings.SwitchRuntimeSettings]
bUseASTCTextures=True
bUseDXTForUITextures=True
bEnableSystemProfilers=True
bAllowCrashReporting=True
; D11.DH Fix for rain particles in Soggy Swamp and Dingy Jungle
r.AllowOcclusionQueries=False
FlushThreshold=10
QueueCommandMemorySize=2
GameServerId=0x26B6CA00
GameServerAccessKey=8eda0c3c
InitialMaxControllers=4
InitialEnableDualStickControllers=true
InitialEnableSingleStickControllers=true
InitialUseHorizontalSingleStick=true
StartupAccountMode=Required 
SaveGameSizeKB=8192
CompressionOverrides=(bOverrideCompressionTimes=True,DurationThreshold=0.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
OpusBehavior=StreamingSoundsOnly
MaxConcurrentHardwareDecodes=2
MaxNumAudioSources=32
bEnableNEXLibrary=false
ProgramId=0x01006c100ec08000
NifmRequestPolicy=Once
MallocHeapSizeKB=32768
MainThreadStackSizeKB=128
TouchScreenUsage=None
ApplicationVersion=15
ApplicationVersionString=1.10.0.0
+SupportedLanguages=AmericanEnglish
+SupportedLanguages=BritishEnglish
+SupportedLanguages=LatinAmericanSpanish
+SupportedLanguages=Spanish
+SupportedLanguages=French
+SupportedLanguages=Italian
+SupportedLanguages=Japanese
+SupportedLanguages=Korean
+SupportedLanguages=Portuguese
+SupportedLanguages=Russian
+SupportedLanguages=German
+SupportedLanguages=SimplifiedChinese
+SupportedLanguages=TraditionalChinese
+LocalizedTitles=(Language=AmericanEnglish,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=BritishEnglish,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=LatinAmericanSpanish,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=Spanish,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=French,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=Italian,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=Japanese,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=Korean,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=Portuguese,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=Russian,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=German,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=SimplifiedChinese,Title="Minecraft Dungeons",Publisher="Mojang AB")
+LocalizedTitles=(Language=TraditionalChinese,Title="Minecraft Dungeons",Publisher="Mojang AB")
+AgeRatings=(Organization=ESRB,Age=10)
+AgeRatings=(Organization=CERO,Age=0)
+AgeRatings=(Organization=PEGI,Age=7)
+AgeRatings=(Organization=PEGIBBFC,Age=7)
+AgeRatings=(Organization=PEGIPortugal,Age=7)
+AgeRatings=(Organization=ClassInd,Age=10)
+AgeRatings=(Organization=Russian,Age=6)
+AgeRatings=(Organization=ACB,Age=8)
+AgeRatings=(Organization=OFLC,Age=8)
+AgeRatings=(Organization=USK,Age=12)
+AgeRatings=(Organization=GRACGCRB,Age=0)

[TextureStreaming]
PoolSize=400
MemoryMargin=50

[/Script/Engine.RendererSettings]
Gamma=2.2
r.TonemapperGamma=2.2
FX.AllowGPUParticles=0
r.AllowPointLightCubemapShadows=0
r.TranslucencyLightingVolumeDim=4
r.TranslucentLightingVolume=0

[/Script/Engine.NetworkSettings]
n.VerifyPeer=true

[HTTP.Curl]
MaxTotalConnections=1

[XSAPI.Curl]
MaxTotalConnections=3

[WebSockets.LibWebSockets]
ThreadTargetFrameTimeInSeconds=0.05
ThreadMinimumSleepTimeInSeconds=0.03333333

[Audio]
AudioDeviceModuleName=SwitchAudio
; uncomment the following line and comment the above line to enable software audio mixer
; AudioDeviceModuleName=SwitchAudioMixer

; Defines a platform-specific volume headroom (in dB) for audio to provide better platform consistency with respect to volume levels.
PlatformHeadroomDB=-3

[SystemSettings]
AudioThread.AboveNormalPriority=1
AudioThread.EnableAudioThreadWait=0