
[Windows DeviceProfile]
+CVars=t.MaxFPS=144

[XboxOne DeviceProfile]
DeviceType=XboxOne
BaseProfileName=
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.TemporalAA.Upsampling=1
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=0
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.VolumetricFog=0
+CVars=r.SeparateTranslucency=0
+CVars=r.PostProcessAAQuality=3
+CVars=r.AmbientOcclusionMaxQuality=100
+CVars=r.Shaders.FlowControlMode=2
+CVars=r.AmbientOcclusion.Compute=2
+CVars=r.TranslucencyLightingVolumeDim=32
+CVars=r.VolumetricFog.GridPixelSize=16
+CVars=r.VolumetricFog.GridSizeZ=64
+CVars=r.SSR.Quality=0
+CVars=r.ReflectionEnvironment=0
+CVars=r.Filter.SizeScale=0.1
+CVars=Dungeons.Instancing.Enabled=1
+CVars=Engine.DoAsyncLoadingWhileWaitingForVSync=0
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[XboxOne_S DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=0.01
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.TemporalAA.Upsampling=1
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=0
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.VolumetricFog=0
+CVars=r.SeparateTranslucency=0
+CVars=r.PostProcessAAQuality=3
+CVars=r.AmbientOcclusionMaxQuality=100
+CVars=r.Shaders.FlowControlMode=2
+CVars=r.AmbientOcclusion.Compute=2
+CVars=r.TranslucencyLightingVolumeDim=32
+CVars=r.VolumetricFog.GridPixelSize=16
+CVars=r.VolumetricFog.GridSizeZ=64
+CVars=r.SSR.Quality=0
+CVars=r.ReflectionEnvironment=0
+CVars=r.Filter.SizeScale=0.1
+CVars=Dungeons.Instancing.Enabled=1
+CVars=Engine.DoAsyncLoadingWhileWaitingForVSync=0
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[XboxOne_Scorpio DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=0.01
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.TemporalAA.Upsampling=1
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=0
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.VolumetricFog=0
+CVars=r.Shaders.FlowControlMode=2
+CVars=r.AmbientOcclusion.Compute=2
+CVars=r.TranslucencyLightingVolumeDim=64
+CVars=r.VolumetricFog.GridPixelSize=16
+CVars=r.VolumetricFog.GridSizeZ=64
+CVars=r.SSR.Quality=0
+CVars=r.ReflectionEnvironment=0
+CVars=r.Filter.SizeScale=0.1
+CVars=Dungeons.Instancing.Enabled=1
+CVars=Engine.DoAsyncLoadingWhileWaitingForVSync=0
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[XboxOne_Lockhart DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.TemporalAA.Upsampling=1
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.VolumetricFog=0
+CVars=Dungeons.Instancing.Enabled=1
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[XboxOne_Series_X DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=8.33
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=1
+CVars=t.MaxFPS=120
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.AllowOcclusionQueries=True
+CVars=r.VolumetricFog=0
;+CVars=r.SeparateTranslucency=0
+CVars=r.PostProcessAAQuality=3
+CVars=r.AmbientOcclusionMaxQuality=0
+CVars=Dungeons.Instancing.Enabled=1
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[XboxOne_Series_X_1080p DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=8.33
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.setres=1920x1080f
+CVars=r.Vsync=0
+CVars=t.MaxFPS=120
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=3
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.AllowOcclusionQueries=True
+CVars=r.VolumetricFog=1
+CVars=Dungeons.Instancing.Enabled=1
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")


[PS4 DeviceProfile]
DeviceType=PS4
BaseProfileName=
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=0.01
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
;60 FPS using vsync is better then setting MaxFPS
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=0
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.AllowOcclusionQueries=True
+CVars=r.VolumetricFog=0
+CVars=r.Shaders.FlowControlMode=2
+CVars=r.AmbientOcclusion.Compute=2
+CVars=r.TranslucencyLightingVolumeDim=64
+CVars=r.VolumetricFog.GridPixelSize=16
+CVars=r.VolumetricFog.GridSizeZ=64
+CVars=r.SSR.Quality=0
+CVars=r.ReflectionEnvironment=0
+CVars=r.Filter.SizeScale=0.1
+CVars=Dungeons.Instancing.Enabled=1
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[PS4_Neo DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=0.01
+CVars=r.DynamicRes.MinScreenPercentage=65
+CVars=r.DynamicRes.MaxScreenPercentage=100
;60 FPS using vsync is better then setting MaxFPS
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=0
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.AllowOcclusionQueries=True
+CVars=r.VolumetricFog=0
+CVars=r.Shaders.FlowControlMode=2
+CVars=r.AmbientOcclusion.Compute=2
+CVars=r.TranslucencyLightingVolumeDim=64
+CVars=r.VolumetricFog.GridPixelSize=16
+CVars=r.VolumetricFog.GridSizeZ=64
+CVars=r.SSR.Quality=0
+CVars=r.ReflectionEnvironment=0
+CVars=r.Filter.SizeScale=0.1
+CVars=Dungeons.Instancing.Enabled=1
+CVars=Engine.DoAsyncLoadingWhileWaitingForVSync=0
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[PS4_Neo_4k DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.PS4Allow4kOutput=1
+CVars=r.setres=2560x1440f
+CVars=r.PS4MaxBackbufferWidth=2560
+CVars=r.PS4MaxBackbufferHeight=1440
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=16.66
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=0.01
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100
;60 FPS using vsync is better then setting MaxFPS
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=0
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=3
+CVars=r.LightFunctionQuality=1
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.AllowOcclusionQueries=True
+CVars=r.VolumetricFog=0
+CVars=r.Shaders.FlowControlMode=2
+CVars=r.AmbientOcclusion.Compute=2
+CVars=r.TranslucencyLightingVolumeDim=64
+CVars=r.VolumetricFog.GridPixelSize=16
+CVars=r.VolumetricFog.GridSizeZ=64
+CVars=Dungeons.Instancing.Enabled=1
+CVars=Engine.DoAsyncLoadingWhileWaitingForVSync=0
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[PS5 DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=8.33
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
;60 FPS using vsync is better then setting MaxFPS
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=1
+CVars=r.AllowOcclusionQueries=True
+CVars=r.Shadow.CSM.MaxCascades=5
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.ShadowQuality=5
+CVars=r.LightFunctionQuality=3
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.7
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.AllowOcclusionQueries=True
+CVars=r.VolumetricFog=1
+CVars=Dungeons.Instancing.Enabled=1
+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=256,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")

[PS5_4k DeviceProfile]
BaseProfileName=PS5
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=1
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=8.33
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=50
+CVars=r.DynamicRes.MaxScreenPercentage=100


[Switch DeviceProfile]
+CVars=Dungeons.Perf.InterleavedTargetingTicks=1
+CVars=npad.MaxControllers=4
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.FrameTimeBudget=33.33
+CVars=r.DynamicRes.TargetedGPUHeadRoomPercentage=3.5
+CVars=r.DynamicRes.MinScreenPercentage=80
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.ScreenPercentage=83.33
; Individual Control over the Screen Percentage in Handheld and Console modes
+CVars=Dungeons.Switch.HandheldScreenPercentage=100
+CVars=Dungeons.Switch.ConsoleScreenPercentage=83.33
;30 FPS using vsync is better then setting MaxFPS
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=2
+CVars=r.GTSyncType=2
+CVars=sg.FoliageQuality=1
+CVars=r.temporalAAsamples=4
+CVars=r.temporalAACurrentFrameWeight=0.2
+CVars=r.tonemapper.sharpen=0.7
+CVars=r.Shadow.MaxResolution=1024
+CVars=r.Shadow.RadiusThreshold=0.025
+CVars=r.Shadow.DistanceScale=0.85
+CVars=r.Shadow.CSMDepthBias=12
+CVars=r.Shadow.CSM.TransitionScale=0.8
+CVars=r.Shadow.CSM.MaxCascades=2
+CVars=r.Shadow.MaxCSMResolution=1024
+CVars=r.VolumetricFog=0
+CVars=r.MobileHDR=True
+CVars=r.DefaultFeature.MotionBlur=False
+CVars=r.DefaultFeature.AutoExposure=False
+CVars=r.DefaultFeature.AntiAliasing=2
+CVars=r.DefaultFeature.AmbientOcclusion=0
+CVars=r.CustomDepthTemporalAAJitter=True
+CVars=r.AllowOcclusionQueries=True
+CVars=r.TranslucencyLightingVolumeDim=4
+CVars=r.TranslucentLightingVolume=0
+CVars=r.AllowPointLightCubemapShadows=0
+CVars=r.AmbientOcclusionLevels=0
+CVars=r.SceneColorFormat=3
+CVars=r.Streaming.PoolSize=400
+CVars=r.PostProcessAAQuality=3
+CVars=r.SSR.Quality=0
+CVars=r.BloomQuality=3
+CVars=r.DepthOfFieldQuality=0
+CVars=r.ShadowQuality=2
+CVars=r.LightFunctionQuality=1
+CVars=r.MaterialQualityLevel=2
+CVars=r.SupportStationarySkylight=0
+CVars=r.SeparateTranslucency=0
+CVars=r.DetailMode=2
+CVars=Dungeons.Instancing.Enabled=1
+CVars=switch.LoopMediaPlayerByReopening=0
+CVars=Engine.DoAsyncLoadingWhileWaitingForVSync=0

+TextureLODGroups=(Group=TEXTUREGROUP_Project01,LODBias=0,LODBias_Smaller=-1,LODBias_Smallest=-1,NumStreamedMips=-1,MipGenSettings=TMGS_NoMipmaps,MinLODSize=1,MaxLODSize=128,MaxLODSize_Smaller=-1,MaxLODSize_Smallest=-1,OptionalLODBias=0,OptionalMaxLODSize=4096,MinMagFilter="Aniso",MipFilter="Point")
[Switch_DynRes60 DeviceProfile]
BaseProfileName=Switch
+CVars=r.DynamicRes.OperationMode=2
+CVars=r.DynamicRes.MaxScreenPercentage=100
+CVars=r.DynamicRes.MaxScreenPercentage=30
+CVars=r.DynamicRes.FrameTimeBudget=16.6
+CVars=r.Vsync=1
+CVars=rhi.SyncInterval=1
+CVars=r.GTSyncType=1