
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=4F3EEF474661C81D511F8188F5647A93
ProjectName=Minecraft Dungeons
CompanyName=Mojang AB
CompanyDistinguishedName=Mojang AB
CopyrightNotice=© 2020 Mojang Synergies AB. TM Microsoft Corporation.
ProjectVersion=1.10.0.0
ProjectDisplayedTitle=NSLOCTEXT("[/Script/EngineSettings]", "07DE5FE64050A1DD6CEB55A263F8A403", "Minecraft Dungeons")
Homepage=minecraft.net
SupportContact=help.minecraft.net/hc/
ProjectDebugTitleInfo=NSLOCTEXT("[/Script/EngineSettings]", "90E8A0DE43B0F84CB8ABD49442D58AB7", "Minecraft Dungeons")
LicensingTerms="https://go.microsoft.com/fwlink/?LinkId=822631"
PrivacyPolicy="https://go.microsoft.com/fwlink/?LinkId=521839"

[/Script/Engine.GameNetworkManager]
ClientAuthorativePosition=true
;Default corrected error set to just shy of half a block (100 units is one bloc, and this is 49^2)
MAXPOSITIONERRORSQUARED=2401.f

[/Script/PlayfabServices.PlayfabServicesSettings]
TitleId=C839E
DevelopmentTitleId=4563


[/Script/Dungeons.PlayerCharacterMovementComponent]
LeniencySpeedMultiplierToggleLimit=2.f
LenientMaxPositionError=300.f
LeniencyOffToggleDelayBiasMs=96

[/Script/Dungeons.PlayerControllerBase]
EnableDebugUIControls = false

[/Script/Dungeons.DungeonsCharacter]
FixedCameraPitch=-45.0
FixedCameraDistance=1500.0

[/Script/Dungeons.AutoTargetDefaultIdle]
Angle=360.0
Radius=2000.0
Weight=0.1

[/Script/Dungeons.AutoTargetDefaultActive]
Angle=110.0
Radius=2000.0
Weight=0.2

[/Script/Dungeons.AutoTargetShootingIdle]
Angle=360.0
Radius=2000.0
Weight=0.3

[/Script/Dungeons.AutoTargetShootingActive]
Angle=40.0
Radius=2000.0
Weight=0.6

[/Script/Dungeons.AutoTargetRangedIdle]
Angle=360.0
Radius=2000.0
Weight=0.3

[/Script/Dungeons.AutoTargetRangedActive]
Angle=60.0
Radius=2000.0
Weight=0.6

[/Script/Dungeons.AutoTarget]
RangeBoost=80.0
bDebugDraw=false
bDebugDrawVerbose=false
bLineEnabled=true
bHighlightEnabled=true
bEnabled=true
bRangedTargetModeEnabled=true
bRangedTargetModeForceRadial=false


[/Script/Dungeons.AmbienceFinder]
+AmbienceRoot="/Game/Decor/Generated/"

[/Script/Dungeons.AssetFinder]
+AssetRoots="/Game/"
+AssetRoots="/Game/Patch1/"
+AssetRoots="/Game/Patch2/"
+AssetRoots="/Game/Content_DLC3/"
+AssetRoots="/Game/Content_DLC4/"
+AssetRoots="/Game/Content_DLC5/"
+AssetRoots="/Game/Content_DLC6/"


[/Script/Dungeons.ItemAssetFinder]
+ItemAssetPaths="Actors/Items/"
+ItemAssetPaths="Actors/Equipment/"

[/Script/Dungeons.EnchantmentAssetFinder]
+EnchantmentAssetPaths="Components/Enchantments/"

[/Script/Dungeons.ArmorPropertyAssetFinder]
+ArmorPropertyAssetPaths="Components/ArmorProperties/"

[/Script/GameplayAbilities.AbilitySystemGlobals]
GameplayCueNotifyPaths=/Game/Cues
AbilitySystemGlobalsClassName=/Script/Dungeons.DungeonsAbilitySystemGlobals
GlobalGameplayCueManagerClass=/Script/Dungeons.DungeonsGameplayCueManager

[/Script/Engine.GameSession]
MaxPlayers=4

[Internationalization]
InternationalizationPreset=All
+LocalizationPaths=%GAMEDIR%Content/Localization/Game
+LocalizationPaths=%ENGINEUSERDIR%Content/Localization/InputKeysLoc

[Staging]
+WhitelistConfigFiles=Dungeons/Config/tags/GameplayTags.ini
+WhitelistConfigFiles=Dungeons/Config/tags/GamplayCues.ini
+WhitelistDirectories=Dungeons/Content/Decor/Prefabs/Apple
+WhitelistDirectories=Dungeons/Content/Sounds/item/fooddrops/eat_wav/apple

[Demo]
Setup=
ShowRewardScreen=False

[Demo/E3]
+Commands=Dungeons.Level.Start DesertTemple 2 2 1337

[Splash]
SkipSplash=false
SplashTime=21

[/Script/Dungeons.SaveIndicator]
DisplaySaveIndicator=true
MinimumDisplayTime=5.0

[/Script/Dungeons.OnlineGame]
DisableOnlineGame=false

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Development
StagingDirectory=(Path="C:/projects/Dungeons/LovikaPacked")
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=True
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=True
bGenerateChunks=True
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bForceOneChunkPerFile=True
MaxChunkSize=0
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
PakFileCompressionFormats=
PakFileAdditionalCompressionOptions=
HttpChunkInstallDataVersion=
IncludePrerequisites=True
IncludeAppLocalPrerequisites=True
bShareMaterialShaderCode=True
bSharedMaterialNativeLibraries=True
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=True
InternationalizationPreset=All
-CulturesToStage=en
+CulturesToStage=en
+CulturesToStage=sv-SE
+CulturesToStage=es-ES
+CulturesToStage=es-MX
+CulturesToStage=fr-FR
+CulturesToStage=it-IT
+CulturesToStage=ja-JP
+CulturesToStage=ko-KR
+CulturesToStage=pl-PL
+CulturesToStage=pt-BR
+CulturesToStage=pt-PT
+CulturesToStage=ru-RU
+CulturesToStage=de-DE
+CulturesToStage=zh-CN
+CulturesToStage=zh-TW
bCookAll=False
bCookMapsOnly=False
bCompressed=False
bEncryptIniFiles=False
bEncryptPakIndex=False
GenerateEarlyDownloaderPakFile=False
bSkipEditorContent=True
bSkipMovies=False
-EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.icu
-EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.brk
-EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.res
-EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.nrm
-EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.cfu
-EarlyDownloaderPakFileFiles=...\Content\Localization\...\*.*
-EarlyDownloaderPakFileFiles=...\Content\Localization\*.*
-EarlyDownloaderPakFileFiles=-...\Content\Localization\Game\...\*.*
-EarlyDownloaderPakFileFiles=-...\Content\Localization\Game\*.*
-EarlyDownloaderPakFileFiles=...\Config\...\*.ini
-EarlyDownloaderPakFileFiles=...\Config\*.ini
-EarlyDownloaderPakFileFiles=...\Engine\GlobalShaderCache*.bin
-EarlyDownloaderPakFileFiles=...\Content\ShaderArchive-Global-*.ushaderbytecode
-EarlyDownloaderPakFileFiles=...\Content\Slate\*.*
-EarlyDownloaderPakFileFiles=...\Content\Slate\...\*.*
-EarlyDownloaderPakFileFiles=...\*.upluginmanifest
-EarlyDownloaderPakFileFiles=...\*.uproject
-EarlyDownloaderPakFileFiles=...\global_sf*.metalmap
+EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.icu
+EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.brk
+EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.res
+EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.nrm
+EarlyDownloaderPakFileFiles=...\Content\Internationalization\...\*.cfu
+EarlyDownloaderPakFileFiles=...\Content\Localization\...\*.*
+EarlyDownloaderPakFileFiles=...\Content\Localization\*.*
+EarlyDownloaderPakFileFiles=...\Content\Certificates\...\*.*
+EarlyDownloaderPakFileFiles=...\Content\Certificates\*.*
+EarlyDownloaderPakFileFiles=-...\Content\Localization\Game\...\*.*
+EarlyDownloaderPakFileFiles=-...\Content\Localization\Game\*.*
+EarlyDownloaderPakFileFiles=...\Config\...\*.ini
+EarlyDownloaderPakFileFiles=...\Config\*.ini
+EarlyDownloaderPakFileFiles=...\Engine\GlobalShaderCache*.bin
+EarlyDownloaderPakFileFiles=...\Content\ShaderArchive-Global-*.ushaderbytecode
+EarlyDownloaderPakFileFiles=...\Content\Slate\*.*
+EarlyDownloaderPakFileFiles=...\Content\Slate\...\*.*
+EarlyDownloaderPakFileFiles=...\*.upluginmanifest
+EarlyDownloaderPakFileFiles=...\*.uproject
+EarlyDownloaderPakFileFiles=...\global_sf*.metalmap
+MapsToCook=(FilePath="/Game/GameModes/Ingame/Ingame")
+MapsToCook=(FilePath="/Game/GameModes/Menu/Menu")
+MapsToCook=(FilePath="/Game/GameModes/Lobby/Lobby")
+DirectoriesToAlwaysCook=(Path="/Game/DataTables/Assets")
+DirectoriesToAlwaysCook=(Path="/Game/PlatformSpecific/PS4")
+DirectoriesToAlwaysCook=(Path="/Game/PlatformSpecific/Switch")
+DirectoriesToAlwaysCook=(Path="/Game/PlatformSpecific/Xbox")
+DirectoriesToAlwaysStageAsUFS=(Path="data")
+DirectoriesToAlwaysStageAsUFS=(Path="UI/cursors")
+DirectoriesToAlwaysStageAsUFS=(Path="Decor/Text")
+DirectoriesToAlwaysStageAsUFS=(Path="SaveIcons")
+DirectoriesToAlwaysStageAsUFS=(Path="Content_DLC4/Text")
+DirectoriesToAlwaysStageAsUFS=(Path="Content_DLC6/Decor/Text")
+DirectoriesToAlwaysStageAsUFS=(Path="Content_Season1/Decor/Text")
+DirectoriesToAlwaysStageAsUFS=(Path="Content_Spooky2021/Decor/Text")
bNativizeBlueprintAssets=False
bNativizeOnlySelectedBlueprints=False


[/Script/Engine.AssetManagerSettings]
-PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass=/Script/Engine.World,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")))
-PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass=/Script/Engine.PrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")))
+PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass=/Script/Engine.PrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/")),SpecificAssets=,Rules=(Priority=-1,bApplyRecursively=False,ChunkId=-1,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="ItemPrimaryDataAsset",AssetBaseClass=/Script/Dungeons.ItemPrimaryDataAsset,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=,SpecificAssets=(/Game/Packaging/ItemPrimaryAsset.ItemPrimaryAsset),Rules=(Priority=10,bApplyRecursively=True,ChunkId=4,CookRule=AlwaysCook))
+PrimaryAssetTypesToScan=(PrimaryAssetType="MobPrimaryDataAsset",AssetBaseClass=/Script/Dungeons.MobPrimaryDataAsset,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=,SpecificAssets=(/Game/Actors/Characters/Enemies/MobDataAssetLabel.MobDataAssetLabel),Rules=(Priority=-1,bApplyRecursively=True,ChunkId=-1,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="MissionPrimaryDataAssetBase",AssetBaseClass=/Script/Dungeons.MissionPrimaryDataAssetBase,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/Packaging")),SpecificAssets=,Rules=(Priority=-1,bApplyRecursively=True,ChunkId=-1,CookRule=AlwaysCook))
+PrimaryAssetTypesToScan=(PrimaryAssetType="PropertyPrimaryDataAsset",AssetBaseClass=/Script/Dungeons.PropertyPrimaryDataAsset,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=,SpecificAssets=(/Game/Components/PropertiesDataAsset.PropertiesDataAsset),Rules=(Priority=-1,bApplyRecursively=True,ChunkId=-1,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="DlcPrimaryDataAsset",AssetBaseClass=/Script/Dungeons.DlcPrimaryDataAsset,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/Packaging/Dlc")),Rules=(Priority=-1,bApplyRecursively=True,ChunkId=-1,CookRule=AlwaysCook))
+PrimaryAssetTypesToScan=(PrimaryAssetType="ItemInstanceInventoryDataLookup",AssetBaseClass=/Script/Dungeons.ItemInstanceInventoryDataLookup,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=,SpecificAssets=(/Game/Packaging/ItemInstanceDataLookup.ItemInstanceDataLookup),Rules=(Priority=-1,bApplyRecursively=True,ChunkId=4,CookRule=AlwaysCook))
+PrimaryAssetTypesToScan=(PrimaryAssetType="MissionPrimaryDataAssetBase2",AssetBaseClass=/Script/Dungeons.MissionPrimaryDataAssetBase2,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/Packaging")),SpecificAssets=(/Game/Packaging/Dlc/NetherHypermission2PrimaryAsset.NetherHypermission2PrimaryAsset),Rules=(Priority=-1,bApplyRecursively=True,ChunkId=-1,CookRule=AlwaysCook))
bOnlyCookProductionAssets=False
bShouldManagerDetermineTypeAndName=True
bShouldGuessTypeAndNameInEditor=False
bShouldAcquireMissingChunksOnLoad=False
MetaDataTagsForAssetRegistry=()
