#pragma once

//TODO move me to client and to BlockGraphics!!

///Render layers: be aware that the order *is important* to the merged rendering
enum BlockRenderLayer {
	RENDERLAYER_DOUBLE_SIDED = 0,
	RENDERLAYER_BLEND,
	RENDERLAYER_WATER,
	RENDERLAYER_OPAQUE,
	RENDERLAYER_OPAQUE_ADDITIONAL_ZEROALPHA_GEOMETRY,
	RENDERLAYER_ENDPORTAL,
	RENDERLAYER_OPTIONAL_ALPHATEST,
	RENDERLAYER_ALPHATEST,
	RENDERLAYER_ALPHATEST_FOILAGE,
	RENDERLAYER_SEASONS_OPAQUE,
	RENDERLAYER_SEASONS_OPTIONAL_ALPHATEST,
	RENDERLAYER_ALPHATEST_SINGLE_SIDE,
	RENDERLAYER_LAVA,
	RENDERLAYER_TORCH,
	RENDERLAYER_FIRE,
	RENDERLAYER_LEAVES,
	RENDERLAYER_OPAQUE_FILL,
	RENDERLAYER_VOID,

	_RENDERLAYER_COUNT
};


