[/Script/Engine.GameSession]
;Always on chat audio
bRequiresPushToTalk=false

[/Script/MoviePlayer.MoviePlayerSettings]
+StartupMovies=splash_intro_720


[/Script/Dungeons.SaveIndicator]
DisplaySaveIndicator=true
MinimumDisplayTime=3.0

[EntitlementMapping]
+EntitlementMap=(EntitlementName="game_dungeons_dlc_1", PlatformSkuId="Microsoft.57557416C1FDE")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_2", PlatformSkuId="Microsoft.594097A1B01A7")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_1", PlatformSkuId="Microsoft.HeroDLC")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_2", PlatformSkuId="Microsoft.HeroDLC")
+EntitlementMap=(EntitlementName="game_dungeons_hero_cape_1", PlatformSkuId="Microsoft.HeroDLC")
+EntitlementMap=(EntitlementName="game_dungeons_hero_skin_1", PlatformSkuId="Microsoft.HeroDLC")
+EntitlementMap=(EntitlementName="game_dungeons_hero_skin_2", PlatformSkuId="Microsoft.HeroDLC")
+EntitlementMap=(EntitlementName="game_dungeons_hero_pet_1", PlatformSkuId="Microsoft.HeroDLC")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_3", PlatformSkuId="Microsoft.DLC3")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_4", PlatformSkuId="Microsoft.DLC4")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_5", PlatformSkuId="Microsoft.DLC5")
+EntitlementMap=(EntitlementName="game_dungeons_dlc_6", PlatformSkuId="Microsoft.DLC6")

[ProductIdMapping]
+ProductMap=(DlcName="HeroDLC", PlatformProductId="524e5039-5346-3039-c04d-444246354900")
+ProductMap=(DlcName="JungleDLC", PlatformProductId="574d5039-5156-3043-c04a-563034516c00")
+ProductMap=(DlcName="IceDLC", PlatformProductId="375a4d39-5044-304e-c037-564650365200")
+ProductMap=(DlcName="MountainsDLC", PlatformProductId="484a4e39-4d30-3058-c044-323436471500")
+ProductMap=(DlcName="NetherDLC", PlatformProductId="4d465039-3834-3044-c054-523950565100")
+ProductMap=(DlcName="OceansDLC", PlatformProductId="51544d39-3647-304c-c032-4a5837545300")
+ProductMap=(DlcName="TheEndDLC", PlatformProductId="4a574d39-5644-3032-c04e-51334a475600")