[Audio]
;AudioDeviceModuleName=XAudio2

; Uncomment below (and comment above) to use multi-platform mixer module by default
AudioDeviceModuleName=AudioMixerXAudio2

; Defining below allows switching to audio mixer using -audiomixer commandline
AudioMixerModuleName=AudioMixerXAudio2

[OnlineSubsystem]
DefaultPlatformService=Dungeons
PollingIntervalInMs=20

[/Script/Engine.Player]
ConfiguredInternetSpeed=30000
ConfiguredLanSpeed=30000


[OnlineSubsystemSteam]
bEnabled=true 
SteamDevAppId=1672970
GameServerQueryPort=27015
bRelaunchInSteam=false
GameVersion=1.0.0.0
bVACEnabled=1
bAllowP2PPacketRelay=true
P2PConnectionTimeout=90
Achievement_0_Id="REVIVE_20"
Achievement_1_Id="KILL_50_MOBS"
Achievement_2_Id="KILL_2500_MOBS"
Achievement_3_Id="KILL_50_PASSIVE"
Achievement_4_Id="KILL_50_ENCHANTED"
Achievement_5_Id="LVL_10"
Achievement_6_Id="LVL_25"
Achievement_7_Id="LVL_50"
Achievement_8_Id="FANCY_CHEST"
Achievement_9_Id="CHEST_100"
Achievement_10_Id="EMERALD_1000"
Achievement_11_Id="EMERALD_5000"
Achievement_12_Id="EAT_200_FOOD"
Achievement_13_Id="COMPLETE_SQUID_COAST"
Achievement_14_Id="COMPLETE_CREEPER_WOODS"
Achievement_15_Id="COMPLETE_LEVEL_GROUP1"
Achievement_16_Id="COMPLETE_LEVEL_GROUP2"
Achievement_17_Id="COMPLETE_LEVEL_GROUP3"
Achievement_18_Id="DEFEAT_ARCH_ILLAGER_ANY"
Achievement_19_Id="DEFEAT_ARCH_ILLAGER_HARD"
Achievement_20_Id="TNT_KILL_10"
Achievement_21_Id="FULL_ENCHANTED_GEAR_SET"
Achievement_22_Id="FULLY_UPGRADE_ENCHANTMENT"
Achievement_23_Id="BEAST_MASTER"
Achievement_24_Id="DEFEAT_JUNGLE_ABOMINATION_ADVENTURE"
Achievement_25_Id="COMPLETE_PANDA_PLATEAU"
Achievement_26_Id="OCELOT_ARMOUR"
Achievement_27_Id="COMPLETE_DINGY_JUNGLE_POTION"
Achievement_28_Id="DEFEAT_MOOSHROOM_MONSTROSITY_ITEMS"
Achievement_29_Id="DEFEAT_WRETCHED_WRAITH_ADVENTURE"
Achievement_30_Id="COMPLETE_LOST_SETTLEMENT"
Achievement_31_Id="ICE_WAND_KILL_5"
Achievement_32_Id="ICE_SLIDE_500"
Achievement_33_Id="ICE_NO_WEAPONS"
Achievement_34_Id="COMPLETE_GALE_SANCTUM_ADVENTURE"
Achievement_35_Id="COMPLETE_COLOSSAL_RAMPART"
Achievement_36_Id="KILL_10_MOUNTAINEER_TEMPEST_KNIFE_TIMED"
Achievement_37_Id="UPDRAFT_WINDCALLERS_3"
Achievement_38_Id="LLAMA_OFFERING"
Achievement_39_Id="KILL_RAVAGER_SQUALL_GOLEM_TIMED"
Achievement_40_Id="DEFEAT_TEMPEST_GOLEM_PETS"
Achievement_41_Id="COMPLETE_OBSIDIAN_PINNACLE_APOCALYPSE5"
Achievement_42_Id="COMPLETE_DAILY_TRIAL_EMERALD_ARMOUR"
Achievement_43_Id="DEATH_BARTER_2"
Achievement_44_Id="COMPLETE_NETHER_WASTES_APOCALYPSE"
Achievement_45_Id="COMPLETE_NETHER_SECRET_APOCALYPSE_PLUS"
Achievement_46_Id="DEFEAT_ANCIENT_15"
Achievement_47_Id="COLLECT_500_GOLD"
Achievement_48_Id="MERCHANTS_6"
Achievement_49_Id="GONG_6"
Achievement_50_Id="SPINWHEEL_70"
Achievement_51_Id="HYPERMISSIONS_4"
Achievement_52_Id="HOMECOMING"
Achievement_53_Id="EFFECTS_TRIGGER_5"
Achievement_54_Id="COMPLETE_ABYSSAL_MONUMENT_APOCALYPSE"
Achievement_55_Id="COMPLETE_RADIANT_RAVINE_APOCALYPSE_PLUS"
Achievement_56_Id="GLOWSQUID_ICEWAND"
Achievement_57_Id="FISHING_ROD"
Achievement_58_Id="LOST_CONDUIT"
Achievement_59_Id="RELAX_BUBBLE_COLUMN"
Achievement_60_Id="NO_OXYGEN_60"
Achievement_61_Id="TRIDENT"
Achievement_62_Id="RAID_CAPTAIN_10"
Achievement_63_Id="BUBBLE_BOW"
Achievement_64_Id="TRAVEL_THROUGH_END_PORTAL"
Achievement_65_Id="ENTER_STRONGHOLD_VAULT"
Achievement_66_Id="DEFEAT_BROKEN_HEART_OF_ENDER"
Achievement_67_Id="UNLOCK_ALL_ITEMS_BASE_AND_DLC"
Achievement_68_Id="REACH_TOP_OF_BROKEN_CITADEL_NO_HIT_SHULKERS_BULLET"
Achievement_79_Id="DEFEAT_1000_ENDERLINGS_WITH_OBSIDIAN_BLADE"
Achievement_70_Id="SURVIVE_AFFLICTED_BY_VOIDED_X999"
Achievement_71_Id="ELYTRA_DIVE_ATTACK_12_ENEMIES_AT_ONCE"
Achievement_72_Id="BURNING_BREW_DEFEAT_MOB_WITH_FIRE_ENCHANTMENT"
Achievement_73_Id="SQUID_COAST_EASTER_EGG"