//------------------------------------------------------------------------------
// <copyright file="UnrealServiceContainer.h" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------

#pragma once

#include "UTFAnnotations.h"
#include "UnrealToolsServiceTypes.h"

namespace Microsoft { namespace Internal { namespace GamesTest { namespace UnrealToolsFramework {

    /** Forward declaration. */
    class IUnrealToolsService;

    /** Type for shared UTF service pointers. */
    typedef TSharedPtr<IUnrealToolsService> UnrealToolsServicePtr;
    
    /** Type for the map containing the services. */
    typedef TMap<EUTFServiceType, UnrealToolsServicePtr> UTFServicesMap;

    /**
     * Singleton container for the services managed
     * by the Unreal Tools Framework.
     */
    class FUnrealServiceContainer
    {
    public:
        /** Gets the only instance of this class. */
        static FUnrealServiceContainer& GetInstance();

        /** Returns a const iterator for the services. */
        UTFServicesMap::TConstIterator ConstIterator() const;

        /** Returns an iterator for the services. */
        UTFServicesMap::TIterator Iterator();

        /**
         * Returns the registered service matching the specified type
         * or an invalid pointer if not found.
         */
        UnrealToolsServicePtr GetService(EUTFServiceType Type) const;

        /**
         * Adds a service of the specified type.
         * Adding two services of the same type is not allowed and will
         * result on the service not being added and a failure return code.
         * @param Type - Type of the service to add.
         * @param Service - Service to add.
         * @return A code indicating either success or failure.
         */
        UTF_ANNOTATE_HRESULT_METHOD HRESULT AddService(EUTFServiceType Type, UnrealToolsServicePtr Service);

        /** Removes all elements from the container. */
        void Empty();

    private:
        /** Hide constructor to make this class a singleton. */
        FUnrealServiceContainer();

        /** Make sure these aren't generated by the compiler. */
        FUnrealServiceContainer(const FUnrealServiceContainer&);
        void operator=(const FUnrealServiceContainer&);

    private:
        /** Services that have been registered to be managed by UTF. */
        UTFServicesMap Services;
    };

}}}}
