//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.GNS.BotBrain.Lovika.Resources.BotBrains {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Parameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.GNS.BotBrain.Lovika.Resources.BotBrains.Parameters", typeof(Parameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowZAxis.
        /// </summary>
        public static string AllowZAxis {
            get {
                return ResourceManager.GetString("AllowZAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttackRadius.
        /// </summary>
        public static string AttackRadius {
            get {
                return ResourceManager.GetString("AttackRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameStateMaxAge.
        /// </summary>
        public static string GameStateMaxAge {
            get {
                return ResourceManager.GetString("GameStateMaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleDistanceThreshold.
        /// </summary>
        public static string IdleDistanceThreshold {
            get {
                return ResourceManager.GetString("IdleDistanceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleWaitTime.
        /// </summary>
        public static string IdleWaitTime {
            get {
                return ResourceManager.GetString("IdleWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxDistance.
        /// </summary>
        public static string MaxDistance {
            get {
                return ResourceManager.GetString("MaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerMaxAge.
        /// </summary>
        public static string PlayerMaxAge {
            get {
                return ResourceManager.GetString("PlayerMaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegexFilters.
        /// </summary>
        public static string RegexFilters {
            get {
                return ResourceManager.GetString("RegexFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SameFrequency.
        /// </summary>
        public static string SameFrequency {
            get {
                return ResourceManager.GetString("SameFrequency", resourceCulture);
            }
        }
    }
}
